avator_1:
  preparation: false
  bbox_shift: 5
  video_path: "data/video/sun.mp4"
  audio_clips:
    audio_1: "data/audio/sun.wav"
 
avator_2:
  preparation: true
  bbox_shift: 5
  video_path: "asset/demo/musk"
  audio_clips:
    audio_1: "data/audio/yongen.wav"
